easyvideoproject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from video import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^video/(?P<vid>\d+)/$', views.videoDetail, name='videoDetail'),
    url(r'^history/$', views.viewHistory, name="viewHistory"),
    url(r'^cate/(?P<cateid>\d+)/$', views.videoCate, name='videoCate'),
    url(r'^login/$', views.login, name="login"),
    url(r'^register/$', views.register, name="register"),
    url(r'^like/$', views.like, name='like'),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }, name='media'),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT, }, name='static'),
    url(r'^check_code', views.check_code, name='check_code'),
    url(r'^logout/$', views.logOut, name="logout"),
]

video/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

# 视频分类
class Cate(models.Model):
    name = models.CharField(verbose_name="分类名称", max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '分类名称'
        verbose_name_plural = verbose_name


def get_video_path(instance, filename):
    return 'video/{0}/{1}'.format(instance.name, filename)


def get_img_path(instance, filename):
    return 'video_img/{0}/{1}'.format(instance.name, filename)


# 视频
class Video(models.Model):
    name = models.CharField(verbose_name='视频名称', max_length=20)
    link = models.FileField(verbose_name='视频链接', upload_to=get_video_path)
    img = models.ImageField(verbose_name='视频图片', upload_to=get_img_path)
    passwd = models.CharField(verbose_name='播放密码', max_length=10, null=True, blank=True)
    introduce = models.TextField(verbose_name="视频介绍")
    cate = models.ForeignKey(Cate, verbose_name='视频分类')
    hour = models.CharField(verbose_name="视频时长", max_length=10)
    views = models.IntegerField(verbose_name='观看次数', default=0)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    create_date = models.DateField(verbose_name='创建日期', auto_now_add=True)
    status = models.CharField(verbose_name='状态', choices=(('上线', '上线'), ('下线', '下线')), max_length=10, default="上线")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '视频'
        verbose_name_plural = verbose_name


# 视频标签
class Label(models.Model):
    video = models.ForeignKey(Video, verbose_name="视频")
    label = models.CharField(verbose_name="标签名", max_length=10)

    def __str__(self):
        return self.label

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name


# 视频专辑
class Set(models.Model):
    name = models.CharField(verbose_name="专辑名称", max_length=20)
    video = models.ForeignKey(Video, verbose_name='视频名称')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '专辑'
        verbose_name_plural = verbose_name


# 视频点赞
class Likes(models.Model):
    video = models.ForeignKey(Video, verbose_name='视频')
    user = models.ForeignKey(User, verbose_name='用户')
    time = models.DateTimeField(verbose_name='时间', auto_now_add=True)

    def __str__(self):
        return str(self.video)

    class Meta:
        verbose_name = '点赞'
        verbose_name_plural = verbose_name


# 观看历史
class History(models.Model):
    video = models.ForeignKey(Video)
    user = models.ForeignKey(User)
    view_date = models.DateTimeField(verbose_name='观看时间', auto_now_add=True)

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = '观看历史'
        verbose_name_plural = verbose_name

templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html lang='zh_CN'>
<head>
    <title>{% block title %}{% endblock %} - Easy Video</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel='stylesheet' type='text/css' media="all"/>
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' media="all"/>
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
</head>
<body>
<!-- 导航栏 -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'index' %}"><h1><img src="{% static 'images/logo.png' %}" alt=""
                                                                      width=153 height=49/></h1></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <div class="top-search">
                <form class="navbar-form navbar-right">
                    <input type="text" class="form-control" placeholder="搜索...">
                    <input type="submit" value=" ">
                </form>
            </div>
            <div class="header-top-right">
                {% if user.is_authenticated %}
                    <div class="signin"><span class="play-icon popup-with-zoom-anim">{{ user.username }}</span></div>
                    <div class="signin"><a href="{% url 'logout' %}" class="play-icon popup-with-zoom-anim">注销</a></div>
                {% else %}
                    <div class="signin"><a href="{% url 'register' %}" class="play-icon popup-with-zoom-anim">注册</a>
                    </div>
                    <div class="signin"><a href="{% url 'login' %}" class="play-icon popup-with-zoom-anim">登录</a></div>
                {% endif %}
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</nav>
<!-- 左侧菜单 -->
<div class="col-sm-3 col-md-2 sidebar">
    <div class="drop-navigation drop-navigation">
        <ul class="nav nav-sidebar">
            <li><a></a></li>
            <li class="active">
                <a href="{% url 'index' %}" class="home-icon"><span class="glyphicon glyphicon-home"></span>首页</a>
            </li>
            {% for m in menu_list %}
                <li>
                    <a href="{% url 'videoCate' m.id %}" class="user-icon"><span
                            class="glyphicon glyphicon-home glyphicon-th"></span>{{ m.name }}</a>
                </li>
            {% endfor %}
            <li>
                <a href="{% url 'viewHistory' %}" class="sub-icon"><span
                        class="glyphicon glyphicon-home glyphicon-hourglass"></span>观看历史</a>
            </li>
        </ul>
        <div class="side-bottom">
            <div class="side-bottom-icons">
                <ul class="nav2">
                    <li><img src="{% static 'images/ma1.jpg' %}"/></li>
                </ul>
            </div>
            <div class="copyright"><p>Copyright &copy; 2017 Easy Video</p></div>
        </div>
    </div>
</div>
<!-- 左侧菜单结束 -->
<!-- 右侧内容 -->
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    {% block right-content %}
    {% endblock right-content %}
</div>
<div class="clearfix"></div>
{#    <script src="{% static 'js/bootstrap.min.js' %}"></script>#}
</body>
</html>

templates/cate.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} {{catename.name}} {% endblock %}
{% block right-content %}
    <div class="show-top-grids">
        <div class="col-sm-10 show-grid-left main-grids">
            <div class="recommended">
                <div class="">
                    <div class="recommended-info">
                        <div class="heading">
                            <h3>{{ catename }}</h3>
                        </div>
                        <div class="heading-right">
                            <a href="#small-dialog8" class="play-icon popup-with-zoom-anim">订阅</a>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                    {% if cate_video_list %}
                    {% for item in cate_video_list %}
                    <div class="col-md-3 resent-grid recommended-grid movie-video-grid">
                        <div class="resent-grid-img recommended-grid-img">
                            <a href="{% url 'videoDetail' item.id %}"><img src="/media/{{item.img}}" alt="" /></a>
                            <div class="time small-time show-time movie-time">
                                <p>{{item.hour|slice:"4:9"}}</p>
                            </div>
                        </div>
                        <div class="resent-grid-info recommended-grid-info recommended-grid-movie-info">
                            <h5>
                                <a href="single.html" class="title">{{item.name}}</a>
                                 <!--<p class="views views-info">{{item.views}} 观看</p>-->
                            </h5>
                            <ul>

                            </ul>
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}
                    <div class="clearfix"> </div>
                    {% include 'pagination.html' %}
                </div>
            </div>
        </div>
        <div class="col-md-2 show-grid-right">
            <h3>子分类</h3>
            {% if subcate %}
            {% for i in subcate %}
            <div class="show-right-grids">
                <ul>
                    <li class="tv-img"><a href="#"><img src="images/mv.png" alt="" /></a></li>
                    <li><a href="#">English Movies</a></li>
                </ul>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="clearfix"> </div>
    </div>
{% endblock right-content %}

templates/history.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}观看历史{% endblock %}
{% block right-content %}
    <div class="main-grids news-main-grids">
        <div class="recommended-info">
            <h3>{{ user.username }}的观看历史</h3>
            <p class="history-text">
            </p>
            {% if cate_video_list %}
                {% for i in cate_video_list %}
                    <div class="history-grids">
                        <div class="col-md-1 history-left">
                            <p>{{ i.view_date|date:"Y" }}</p>
                        </div>
                        <div class="col-md-11 history-right">
                            <h5>{{ i.video.name }}</h5>
                            <p>{{ i.view_date }} - {{ i.video.introduce }}</p>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                {% endfor %}
            {% endif %}
            {% include 'pagination.html' %}
        </div>
    </div>
{% endblock %}

templates/pagination.html
<div id="pagination">
    <ul class="pager">
    {% if cate_video_list.has_previous %}
        <li><a href="?page={{ cate_video_list.previous_page_number }}">&laquo;上一页</a></li>
    {% else %}
        <li>&laquo;上一页</li>
    {% endif %}
        <li>{{ cate_video_list.number }}/{{ cate_video_list.paginator.num_pages }}</li>
    {% if cate_video_list.has_next %}
        <li><a href="?page={{ cate_video_list.next_page_number }}">下一页 &raquo;</a></li>
    {% else %}
        <li>下一页 &raquo;</li>
    {% endif %}
   </ul>
</div>

templates/single.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} {{ video.name }} {% endblock %}
{% block right-content %}
    <div class="show-top-grids">
        <div class="col-sm-8 single-left">
            <div class="song">
                <div class="song-info">
                    <h3>{{ video.name }}</h3>
                </div>

                <div class="video-grid">
                    {% if video.passwd == None %}
                        <video width=600 src="/media/{{ video.link }}" controls preload></video>
                    {% else %}
                        {% if user.is_authenticated %}
                            <video width=600 src="/media/{{ video.link }}" controls preload></video>
                        {% else %}
                            <div class="signin"><h4><strong>对不起！本视频只能登录后观看，你可以</strong></h4></div>
                            <div class="signin"><a href="{% url 'register' %}"
                                                   class="play-icon popup-with-zoom-anim">注册</a></div>
                            <div class="signin"><a href="{% url 'login' %}"
                                                   class="play-icon popup-with-zoom-anim">登录</a></div>
                        {% endif %}
                    {% endif %}
                </div>

                <div class="share">
                    <ul>
                        <div class="col-md-4">
                            <li style="float:left;"><a href="#" class="icon like">点赞</a></li>
                        </div>
                        <div class="col-md-4">
                            <li style="float:left;"><a href="#" class="icon comment-icon">评论</a></li>
                        </div>
                        <div class="col-md-4">
                            <li class="view" style="float:left;">{{ video.views }} 次观看</li>
                        </div>
                    </ul>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="published row">
                <div class="col-md-6">
                    <h4>发布于：{{ video.create_date }}</h4>
                    <p>{{ video.introduce }}</p>
                </div>
                <div class="col-md-6">
                    <h4>分类：</h4>
                    <a href="{% url 'videoCate' video.cate.id %}">{{ video.cate.name }}</a>
                </div>
            </div>
            <!-- 评论 -->
            <div class="all-comments">
            </div>
        </div>

        <!-- 相关推荐 -->
        <div class="col-md-4 single-right">
            <h3>Reaction</h3>
            <div class="single-grid-right">
                <!-- 存在专辑 -->
                {% if video_set %}
                    {% for item in video_set %}
                        <div class="single-right-grids">
                            <div class="col-md-4 single-right-grid-left">
                                <a href="{% url 'videoDetail' item.video.id %}"><img src="/media/{{ item.video.img }}"
                                                                                     alt=""/></a>
                            </div>
                            <div class="col-md-8 single-right-grid-right">
                                <a href="{% url 'videoDetail' item.video.id %}" class="title"> {{ item.video }}</a>
                                <p class="views">{{ item.video.views }} views</p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    {% endfor %}
                    <!-- 随机推荐 -->
                {% else %}
                    {% for item in random_video %}
                        <div class="single-right-grids">
                            <div class="col-md-4 single-right-grid-left">
                                <a href="{% url 'videoDetail' item.video.id %}"><img src="images/r1.jpg" alt=""/></a>
                            </div>
                            <div class="col-md-8 single-right-grid-right">
                                <a href="{% url 'videoDetail' item.video.id %}" class="title"> {{ item.name }}</a>
                                <p class="author"><a href="#" class="author">John Maniya</a></p>
                                <p class="views">{{ item.views }} views</p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
{% endblock right-content %}